### ISSUE TITLE
Builder Context requires Activity only?

### ISSUE THREAD

**Issue by Shohrukhbek** [mreram/ShowCaseView#15] opened 2018-08-20 07:05 UTC
final View view1 = getView().findViewById(R.id.view1);
        final View view2 = getView().findViewById(R.id.view2);
        final View view3 = getView().findViewById(R.id.view3);
        final View view4 = getView().findViewById(R.id.view4);
        final View view5 = getView().findViewById(R.id.view5);

        builder = new GuideView.Builder(getActivity())
                .setTitle("Guide Title Text")
                .setContentText("Guide Description Text\n .....Guide Description Text\n .....Guide Description Text .....")
                .setGravity(GuideView.Gravity.center)
                .setDismissType(GuideView.DismissType.outside)
                .setTargetView(view1)
                .setGuideListener(new GuideView.GuideListener() {
                    @Override
                    public void onDismiss(View view) {
                        switch (view.getId()) {
                            case R.id.view1:
                                builder.setTargetView(view2).build();
                                break;
                            case R.id.view2:
                                builder.setTargetView(view3).build();
                                break;
                            case R.id.view3:
                                builder.setTargetView(view4).build();
                                break;
                            case R.id.view4:
                                builder.setTargetView(view5).build();
                                break;
                            case R.id.view5:
                                return;
                        }
                        mGuideView = builder.build();
                        mGuideView.show();
                    }
                });

        mGuideView = builder.build();
        mGuideView.show();`

Not working with `getActivity()` with error in Log: `void android.view.View.getLocationOnScreen(int[])`. I understand what it tries to say, but wanted to know your answer to.  In general you've done a nice job

**Comment by mreram** [comment] 2019-07-13 16:36
Duplicate of #21

**Closed by mreram** 2019-07-13 16:36 UTC
