### ISSUE TITLE
Setting Listener in Kotlin ?

### ISSUE THREAD

**Issue by tahaak67** [mreram/ShowCaseView#26] opened 2019-04-24 13:38 UTC
Please excuse my question if it sounds too silly but im a beginner and im writing my app with Kotlin, i've implemented the ShowCaseView successfully and its working great when working with one ShowCaseView, im trying to make the app show several ShowCaseViews one after another but im having a hard time doing so in Kotlin, Kotlin dosn't allow overriding for local functions i've also tried to implement the GuideListener Interface in a class and then override onDismiss() fun from there but that didn't help.

below is the code i got working for a single ShowCase
```

fun showTut(title:String,text:String,viewID:View){
    GuideView.Builder(this)
        .setTitle(title)
        .setContentText(text)
        .setTargetView(viewID)
        .setContentTextSize(12)//optional
        .setTitleTextSize(14)//optional
    
        .setDismissType(DismissType.anywhere)
        .build()
        .show()

} 
```

**Comment by mreram** [comment] 2019-07-13 16:39
Duplicate of #23

**Closed by mreram** 2019-07-13 16:39 UTC

**Comment by tahaak67** [comment] 2019-07-13 17:59
I'm not sure how this is supposed to be a duplicate, #23 is all about a skip button but i was just having a problem with implementing the show case view in kotlin.
anyway i was able to solve my problem and accomplish to show the case views one after the other when the user taps, here is a quick example of how i did it:
```
       class mGuideListener:GuideListener{
        override fun onDismiss(view: View) {

        }

    }

\\ calling the first show case view
showTut("some text ","more text",view0,0)


fun showTut(title:String,text:String,viewID:View,type:Int){

val gL: mGuideListener = mGuideListener()

    GuideView.Builder(this)
        .setTitle(title)
        .setContentText(text)
        .setTargetView(viewID)
        .setContentTextSize(12)//optional
        .setTitleTextSize(14)//optional
        .setDismissType(DismissType.anywhere)
        .setGuideListener(GuideListener(){
        gL.onDismiss(viewID)

            when (type){
            0 -> {
                showTut("First message","This is the text of the first message",view1,1)
            }
            1-> {
                showTut("Second message","This is the text of the second message",view2,2)

            }
            2 ->{
                showTut("Third message","This is the text of the 3rd message",view3,3)

            }
                3->{
                    showTut("4th message","This is the text of the 4th message",view4,4)

                }
            }
        })

        .build()
        .show()

} 

```
it might not be the perfect way to do it but at least it works, just wanted to share in case anyone else wants to do the same but don't know how.

**Comment by mreram** [comment] 2019-07-13 19:30
Dear @tahaak67 the better way is implementing sequence feature but currently this is not able so your issue is related to #23 and this feature will be available in the next version.

**Comment by mreram** [comment] 2019-07-13 19:34
And for using listener in kotlin you can use object instead of writing a class:
`.setGuideListener(object : GuideListener(){

}
`

**Comment by mreram** [comment] 2019-07-13 19:38
And for using listener in kotlin you can use object instead of writing a class:
`.setGuideListener(object : GuideListener(){ })`

**Comment by mreram** [comment] 2019-07-13 19:42
And for using listener in kotlin you can use object instead of writing a class:
```
.setGuideListener(object :GuideListener{
    override fun onDismiss(view: View?) {
        TODO("not implemented") 
    }
})
```

Or using Lambda

`.setGuideListener { TODO("not implemented") }
`

**Comment by tahaak67** [comment] 2019-07-17 12:14
> for using listener in kotlin you can use object instead of writing a class:
> 
> ```
> .setGuideListener(object :GuideListener{
>     override fun onDismiss(view: View?) {
>         TODO("not implemented") 
>     }
> })
> ```
> 
> Or using Lambda
> 
> `.setGuideListener { TODO("not implemented") } `

Works perfectly :), thank you very much for your efforts and help.
